"""
What: pure password-hashing and JWT helpers. Nothing here touches the
      database, a FastAPI Request, or a cookie — that keeps every function
      unit-testable without spinning up the app, and mirrors how
      pipeline/llm.py stays framework-free.

Why argon2 for passwords but sha256 for refresh tokens: CLAUDE.md specifies
      argon2 (passlib) for passwords, which are short and human-chosen —
      they need a slow, memory-hard KDF to resist offline guessing. A
      refresh token is a 256-bit random value generated by us; it already
      has far more entropy than any password could, so a fast digest is
      enough to detect a match, and using argon2 there would only make
      every /auth/refresh call slower for no security benefit.

Why HS256 with one shared secret rather than RS256: there's a single
      resource server here (no separate services that only need to verify,
      not issue, tokens), so an asymmetric keypair would add key management
      with no corresponding benefit. HS256 is what CLAUDE.md's "JWT" and
      jwt_secret setting already imply.
"""

from __future__ import annotations

import hashlib
import uuid
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone

import jwt
from passlib.context import CryptContext

from app.core.config import get_settings
from app.core.errors import AppError

_pwd_context = CryptContext(schemes=["argon2"], deprecated="auto")

ALGORITHM = "HS256"


def hash_password(password: str) -> str:
    return _pwd_context.hash(password)


def verify_password(password: str, password_hash: str) -> bool:
    return _pwd_context.verify(password, password_hash)


@dataclass(frozen=True)
class TokenPayload:
    user_id: uuid.UUID
    role: str
    token_type: str
    jti: str | None


def _check_secret_configured() -> None:
    """The default "change-me" secret is fine for a local ALLOW_ANONYMOUS=true
    run (nothing signs a real token in that mode's normal path), but signing
    a token with it once ALLOW_ANONYMOUS=false means real logins would be
    guessable/forgeable. Refuse rather than silently signing with a public
    default."""
    settings = get_settings()
    if settings.jwt_secret == "change-me" and not settings.allow_anonymous:
        raise RuntimeError(
            "JWT_SECRET is still the default 'change-me' while ALLOW_ANONYMOUS=false. "
            "Set a real secret in .env before issuing tokens outside of local dev."
        )


def create_access_token(user_id: uuid.UUID, role: str) -> str:
    _check_secret_configured()
    settings = get_settings()
    now = datetime.now(timezone.utc)
    payload = {
        "sub": str(user_id),
        "role": role,
        "type": "access",
        "iat": now,
        "exp": now + timedelta(minutes=settings.access_token_minutes),
    }
    return jwt.encode(payload, settings.jwt_secret, algorithm=ALGORITHM)


def create_refresh_token(user_id: uuid.UUID) -> tuple[str, str, datetime]:
    """Returns (token, token_hash, expires_at). The caller stores token_hash
    in the refresh_tokens table and sends token back only as the cookie —
    the raw token is never persisted."""
    _check_secret_configured()
    settings = get_settings()
    now = datetime.now(timezone.utc)
    expires_at = now + timedelta(days=settings.refresh_token_days)
    jti = str(uuid.uuid4())
    payload = {
        "sub": str(user_id),
        "type": "refresh",
        "jti": jti,
        "iat": now,
        "exp": expires_at,
    }
    token = jwt.encode(payload, settings.jwt_secret, algorithm=ALGORITHM)
    token_hash = hashlib.sha256(token.encode("utf-8")).hexdigest()
    return token, token_hash, expires_at


def create_password_reset_token(user_id: uuid.UUID) -> tuple[str, str, datetime]:
    """Returns (token, token_hash, expires_at) -- same shape and same
    reasoning as create_refresh_token(): the caller stores token_hash in
    password_reset_tokens and emails the raw token, never persisting it.
    Needs its own jti (like create_refresh_token's) for the same reason:
    JWT iat/exp encode to whole-second Unix timestamps, so two tokens for
    the same user issued in the same second would otherwise be byte-for-
    byte identical and collide on token_hash's unique constraint -- caught
    live by a test that requested three in a tight loop."""
    _check_secret_configured()
    settings = get_settings()
    now = datetime.now(timezone.utc)
    expires_at = now + timedelta(minutes=settings.password_reset_token_minutes)
    payload = {
        "sub": str(user_id),
        "type": "password_reset",
        "jti": str(uuid.uuid4()),
        "iat": now,
        "exp": expires_at,
    }
    token = jwt.encode(payload, settings.jwt_secret, algorithm=ALGORITHM)
    token_hash = hashlib.sha256(token.encode("utf-8")).hexdigest()
    return token, token_hash, expires_at


def hash_refresh_token(token: str) -> str:
    """Same digest create_refresh_token() used, exposed separately so
    api/auth.py can look up a *presented* token by hash without re-deriving
    it from decode_token()'s payload."""
    return hashlib.sha256(token.encode("utf-8")).hexdigest()


def hash_password_reset_token(token: str) -> str:
    """Same digest as hash_refresh_token() -- kept as its own function
    rather than reused so a reader sees which token type each call site is
    actually looking up, not just "some token"."""
    return hashlib.sha256(token.encode("utf-8")).hexdigest()


def decode_token(token: str, *, expected_type: str) -> TokenPayload:
    settings = get_settings()
    try:
        raw = jwt.decode(token, settings.jwt_secret, algorithms=[ALGORITHM])
    except jwt.ExpiredSignatureError:
        raise AppError("TOKEN_EXPIRED", "Token has expired.", status_code=401)
    except jwt.InvalidTokenError:
        raise AppError("TOKEN_INVALID", "Token is invalid.", status_code=401)

    if raw.get("type") != expected_type:
        raise AppError("TOKEN_INVALID", f"Expected a {expected_type} token.", status_code=401)

    return TokenPayload(
        user_id=uuid.UUID(raw["sub"]),
        role=raw.get("role", ""),
        token_type=raw["type"],
        jti=raw.get("jti"),
    )
